// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/yuv_converter.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class YuvConverterBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  YuvConverterBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  YuvConverterBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Converts a 3-plane YUV (I420/YUV420p) image to RGB.
  /// @param y_plane Pointer to the start of the Y plane.
  /// @param u_plane Pointer to the start of the U plane.
  /// @param v_plane Pointer to the start of the V plane.
  /// @param y_stride Stride (bytes per row) of the Y plane.
  /// @param u_stride Stride of the U plane.
  /// @param v_stride Stride of the V plane.
  /// @param width Image width in pixels.
  /// @param height Image height in pixels.
  /// @return A pointer to an RgbImage struct containing the converted data, or NULL on failure.
  /// The caller is responsible for freeing the memory using free_image_memory().
  ffi.Pointer<RgbImage> convert_yuv_to_rgb_planar(
    ffi.Pointer<ffi.Uint8> y_plane,
    ffi.Pointer<ffi.Uint8> u_plane,
    ffi.Pointer<ffi.Uint8> v_plane,
    int y_stride,
    int u_stride,
    int v_stride,
    int width,
    int height,
  ) {
    return _convert_yuv_to_rgb_planar(
      y_plane,
      u_plane,
      v_plane,
      y_stride,
      u_stride,
      v_stride,
      width,
      height,
    );
  }

  late final _convert_yuv_to_rgb_planarPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<RgbImage> Function(
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int,
              ffi.Int,
              ffi.Int,
              ffi.Int,
              ffi.Int)>>('convert_yuv_to_rgb_planar');
  late final _convert_yuv_to_rgb_planar =
      _convert_yuv_to_rgb_planarPtr.asFunction<
          ffi.Pointer<RgbImage> Function(
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              int,
              int,
              int,
              int,
              int)>();

  /// @brief Converts a 2-plane YUV (NV12/NV21) image to RGB.
  /// @param y_plane Pointer to the start of the Y plane.
  /// @param uv_plane Pointer to the start of the interleaved UV plane.
  /// @param y_stride Stride (bytes per row) of the Y plane.
  /// @param uv_stride Stride of the UV plane.
  /// @param uv_pixel_stride Pixel stride of the UV plane (usually 2 for NV12/NV21).
  /// @param width Image width in pixels.
  /// @param height Image height in pixels.
  /// @param format The specific bi-planar format (NV12 or NV21).
  /// @return A pointer to an RgbImage struct containing the converted data, or NULL on failure.
  /// The caller is responsible for freeing the memory using free_image_memory().
  ffi.Pointer<RgbImage> convert_yuv_to_rgb_biplanar(
    ffi.Pointer<ffi.Uint8> y_plane,
    ffi.Pointer<ffi.Uint8> uv_plane,
    int y_stride,
    int uv_stride,
    int uv_pixel_stride,
    int width,
    int height,
    BiplanarFormat format,
  ) {
    return _convert_yuv_to_rgb_biplanar(
      y_plane,
      uv_plane,
      y_stride,
      uv_stride,
      uv_pixel_stride,
      width,
      height,
      format.value,
    );
  }

  late final _convert_yuv_to_rgb_biplanarPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<RgbImage> Function(
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Int,
              ffi.Int,
              ffi.Int,
              ffi.Int,
              ffi.Int,
              ffi.UnsignedInt)>>('convert_yuv_to_rgb_biplanar');
  late final _convert_yuv_to_rgb_biplanar =
      _convert_yuv_to_rgb_biplanarPtr.asFunction<
          ffi.Pointer<RgbImage> Function(ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Uint8>, int, int, int, int, int, int)>();

  /// @brief Frees the memory allocated for an RgbImage struct and its data.
  /// @param image A pointer to the RgbImage to be freed.
  void free_image_memory(
    ffi.Pointer<RgbImage> image,
  ) {
    return _free_image_memory(
      image,
    );
  }

  late final _free_image_memoryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<RgbImage>)>>(
          'free_image_memory');
  late final _free_image_memory =
      _free_image_memoryPtr.asFunction<void Function(ffi.Pointer<RgbImage>)>();
}

/// @brief Represents an RGB image buffer with its dimensions.
final class RgbImage extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Int()
  external int width;

  @ffi.Int()
  external int height;
}

/// @brief Enum to specify the bi-planar YUV format (NV12 or NV21).
enum BiplanarFormat {
  /// Chroma plane is UVUV...
  NV12(0),

  /// Chroma plane is VUVU...
  NV21(1);

  final int value;
  const BiplanarFormat(this.value);

  static BiplanarFormat fromValue(int value) => switch (value) {
        0 => NV12,
        1 => NV21,
        _ => throw ArgumentError('Unknown value for BiplanarFormat: $value'),
      };
}
